### ISSUE TITLE
Dbus And VNC

### ISSUE THREAD

**Issue by DennyM97** [Practicalbutterfly5/kde-on-android#1]
sudo: unable to resolve host localhost: Name or service not known
.
vnc the connection closed unexpectedly

**Comment by Practicalbutterfly5** [comment]
Can you give more details as to which step is failing, and what was the command you ran.

**Comment by DennyM97** [comment]
Viii.
IX.
 Nothing was happening (neofetch on Ubuntu 20.04.05 LTS)....

And this message came after entering the command Xiii.

**Comment by DennyM97** [comment]
sudo do-release-upgrade -f DistUpgradeViewNonInteractive                                                      Checking for a new Ubuntu release
Get:1 Upgrade tool signature [819 B]                    Get:2 Upgrade tool [1267 kB]
Fetched 1268 kB in 0s (0 B/s)                           authenticate 'jammy.tar.gz' against 'jammy.tar.gz.gpg'  extracting 'jammy.tar.gz'
Traceback (most recent call last):
  File "/tmp/ubuntu-release-upgrader-twumszmj/jammy", line 8, in <module>
    sys.exit(main())                                      File "/tmp/ubuntu-release-upgrader-twumszmj/DistUpgrade/DistUpgradeMain.py", line 241, in main
    if app.run():
  File "/tmp/ubuntu-release-upgrader-twumszmj/DistUpgrade/DistUpgradeController.py", line 2042, in run
    return self.fullUpgrade()
  File "/tmp/ubuntu-release-upgrader-twumszmj/DistUpgrade/DistUpgradeController.py", line 1873, in fullUpgrade      if not self.doPostInitialUpdate():
  File "/tmp/ubuntu-release-upgrader-twumszmj/DistUpgrade/DistUpgradeController.py", line 906, in doPostInitialUpdate
    self.quirks.run("PostInitialUpdate")
  File "/tmp/ubuntu-release-upgrader-twumszmj/DistUpgrade/DistUpgradeQuirks.py", line 99, in run
    func()
  File "/tmp/ubuntu-release-upgrader-twumszmj/DistUpgrade/DistUpgradeQuirks.py", line 126, in jammyPostInitialUpdate
    self._fix_missing_nvidia_metapackage()
  File "/tmp/ubuntu-release-upgrader-twumszmj/DistUpgrade/DistUpgradeQuirks.py", line 1492, in _fix_missing_nvidia_metapackage
    nv = NvidiaDetection()
  File "/tmp/ubuntu-release-upgrader-twumszmj/NvidiaDetector/nvidiadetector.py", line 72, in __init__
    self.detection()
  File "/tmp/ubuntu-release-upgrader-twumszmj/NvidiaDetector/nvidiadetector.py", line 113, in detection
    p1 = Popen(['lspci', '-n'], stdout=PIPE, universal_newlines=True)                                             File "/usr/lib/python3.8/subprocess.py", line 858, in __init__                                                    self._execute_child(args, executable, preexec_fn, close_fds,                                                  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child                                             raise child_exception_type(errno_num, err_msg, err_filename)                                                FileNotFoundError: [Errno 2] No such file or directory: 'lspci'
